# Generated by Django 3.1.3 on 2020-11-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymovie',
            name='pubDate',
            field=models.CharField(max_length=50),
        ),
    ]
