# Generated by Django 3.1.3 on 2020-11-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0002_auto_20201123_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymovie',
            name='movie_id',
            field=models.IntegerField(default=35),
        ),
    ]
